<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CadSemanticAssistant.Application\CadSemanticAssistant.Application.csproj" />
    <ProjectReference Include="..\CadSemanticAssistant.Domain\CadSemanticAssistant.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AcCoreMgd">
      <HintPath>$(AutoCADInstallDir)\AcCoreMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="AcDbMgd">
      <HintPath>$(AutoCADInstallDir)\AcDbMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="AcMgd">
      <HintPath>$(AutoCADInstallDir)\AcMgd.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
